# Generated by Django 4.1.13 on 2024-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('member_type', models.CharField(default='normal', max_length=100)),
                ('favorites', models.ManyToManyField(to='myapp.product')),
            ],
        ),
    ]
